// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/simulation.proto

package simulation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion       string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	SafetyEnvelopeJson []byte                 `protobuf:"bytes,3,opt,name=safety_envelope_json,json=safetyEnvelopeJson,proto3" json:"safety_envelope_json,omitempty"`
	ScenarioSuite      string                 `protobuf:"bytes,4,opt,name=scenario_suite,json=scenarioSuite,proto3" json:"scenario_suite,omitempty"` // "standard", "stress", "edge-cases"
	MaxScenarios       int32                  `protobuf:"varint,5,opt,name=max_scenarios,json=maxScenarios,proto3" json:"max_scenarios,omitempty"`   // 0 = run all in suite
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidationRequest) Reset() {
	*x = ValidationRequest{}
	mi := &file_proto_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRequest) ProtoMessage() {}

func (x *ValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRequest.ProtoReflect.Descriptor instead.
func (*ValidationRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ValidationRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *ValidationRequest) GetSafetyEnvelopeJson() []byte {
	if x != nil {
		return x.SafetyEnvelopeJson
	}
	return nil
}

func (x *ValidationRequest) GetScenarioSuite() string {
	if x != nil {
		return x.ScenarioSuite
	}
	return ""
}

func (x *ValidationRequest) GetMaxScenarios() int32 {
	if x != nil {
		return x.MaxScenarios
	}
	return 0
}

type ValidationReport struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ScenariosPassed    int32                  `protobuf:"varint,2,opt,name=scenarios_passed,json=scenariosPassed,proto3" json:"scenarios_passed,omitempty"`
	ScenariosTotal     int32                  `protobuf:"varint,3,opt,name=scenarios_total,json=scenariosTotal,proto3" json:"scenarios_total,omitempty"`
	PassRate           float64                `protobuf:"fixed64,4,opt,name=pass_rate,json=passRate,proto3" json:"pass_rate,omitempty"`
	DeploymentApproved bool                   `protobuf:"varint,5,opt,name=deployment_approved,json=deploymentApproved,proto3" json:"deployment_approved,omitempty"`
	Results            []*ScenarioResult      `protobuf:"bytes,6,rep,name=results,proto3" json:"results,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidationReport) Reset() {
	*x = ValidationReport{}
	mi := &file_proto_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationReport) ProtoMessage() {}

func (x *ValidationReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationReport.ProtoReflect.Descriptor instead.
func (*ValidationReport) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationReport) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ValidationReport) GetScenariosPassed() int32 {
	if x != nil {
		return x.ScenariosPassed
	}
	return 0
}

func (x *ValidationReport) GetScenariosTotal() int32 {
	if x != nil {
		return x.ScenariosTotal
	}
	return 0
}

func (x *ValidationReport) GetPassRate() float64 {
	if x != nil {
		return x.PassRate
	}
	return 0
}

func (x *ValidationReport) GetDeploymentApproved() bool {
	if x != nil {
		return x.DeploymentApproved
	}
	return false
}

func (x *ValidationReport) GetResults() []*ScenarioResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ValidationReport) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ScenarioResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId      string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Passed          bool                   `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	FailureReason   string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Violations      []*SafetyViolation     `protobuf:"bytes,6,rep,name=violations,proto3" json:"violations,omitempty"`
	Metrics         map[string]float64     `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // task_success_rate, stability_margin, etc.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScenarioResult) Reset() {
	*x = ScenarioResult{}
	mi := &file_proto_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioResult) ProtoMessage() {}

func (x *ScenarioResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioResult.ProtoReflect.Descriptor instead.
func (*ScenarioResult) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *ScenarioResult) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ScenarioResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScenarioResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ScenarioResult) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *ScenarioResult) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ScenarioResult) GetViolations() []*SafetyViolation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *ScenarioResult) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type SafetyViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "velocity_exceeded", "force_exceeded", "boundary_breach"
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Magnitude     float64                `protobuf:"fixed64,3,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SafetyViolation) Reset() {
	*x = SafetyViolation{}
	mi := &file_proto_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafetyViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetyViolation) ProtoMessage() {}

func (x *SafetyViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetyViolation.ProtoReflect.Descriptor instead.
func (*SafetyViolation) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *SafetyViolation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SafetyViolation) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *SafetyViolation) GetMagnitude() float64 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

func (x *SafetyViolation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ScenarioRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId         string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	AgentId            string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion       string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	SafetyEnvelopeJson []byte                 `protobuf:"bytes,4,opt,name=safety_envelope_json,json=safetyEnvelopeJson,proto3" json:"safety_envelope_json,omitempty"`
	Parameters         map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // scenario-specific overrides
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScenarioRequest) Reset() {
	*x = ScenarioRequest{}
	mi := &file_proto_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioRequest) ProtoMessage() {}

func (x *ScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioRequest.ProtoReflect.Descriptor instead.
func (*ScenarioRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *ScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ScenarioRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ScenarioRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *ScenarioRequest) GetSafetyEnvelopeJson() []byte {
	if x != nil {
		return x.SafetyEnvelopeJson
	}
	return nil
}

func (x *ScenarioRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ScenarioEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId     string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "started", "step", "violation", "completed", "failed"
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ElapsedSeconds float64                `protobuf:"fixed64,4,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	Metrics        map[string]float64     `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScenarioEvent) Reset() {
	*x = ScenarioEvent{}
	mi := &file_proto_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioEvent) ProtoMessage() {}

func (x *ScenarioEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioEvent.ProtoReflect.Descriptor instead.
func (*ScenarioEvent) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *ScenarioEvent) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ScenarioEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ScenarioEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScenarioEvent) GetElapsedSeconds() float64 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *ScenarioEvent) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ScenarioEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ListScenariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suite         string                 `protobuf:"bytes,1,opt,name=suite,proto3" json:"suite,omitempty"` // filter by suite, empty = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosRequest) Reset() {
	*x = ListScenariosRequest{}
	mi := &file_proto_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosRequest) ProtoMessage() {}

func (x *ListScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosRequest.ProtoReflect.Descriptor instead.
func (*ListScenariosRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *ListScenariosRequest) GetSuite() string {
	if x != nil {
		return x.Suite
	}
	return ""
}

type ListScenariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suites        []*ScenarioSuite       `protobuf:"bytes,1,rep,name=suites,proto3" json:"suites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosResponse) Reset() {
	*x = ListScenariosResponse{}
	mi := &file_proto_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosResponse) ProtoMessage() {}

func (x *ListScenariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosResponse.ProtoReflect.Descriptor instead.
func (*ListScenariosResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{7}
}

func (x *ListScenariosResponse) GetSuites() []*ScenarioSuite {
	if x != nil {
		return x.Suites
	}
	return nil
}

type ScenarioSuite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ScenarioCount int32                  `protobuf:"varint,3,opt,name=scenario_count,json=scenarioCount,proto3" json:"scenario_count,omitempty"`
	Scenarios     []*ScenarioInfo        `protobuf:"bytes,4,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioSuite) Reset() {
	*x = ScenarioSuite{}
	mi := &file_proto_simulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioSuite) ProtoMessage() {}

func (x *ScenarioSuite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioSuite.ProtoReflect.Descriptor instead.
func (*ScenarioSuite) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{8}
}

func (x *ScenarioSuite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScenarioSuite) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScenarioSuite) GetScenarioCount() int32 {
	if x != nil {
		return x.ScenarioCount
	}
	return 0
}

func (x *ScenarioSuite) GetScenarios() []*ScenarioInfo {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

type ScenarioInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"` // "easy", "medium", "hard", "edge-case"
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`             // "locomotion", "manipulation", "navigation"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioInfo) Reset() {
	*x = ScenarioInfo{}
	mi := &file_proto_simulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioInfo) ProtoMessage() {}

func (x *ScenarioInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioInfo.ProtoReflect.Descriptor instead.
func (*ScenarioInfo) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{9}
}

func (x *ScenarioInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScenarioInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScenarioInfo) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *ScenarioInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_proto_simulation_proto protoreflect.FileDescriptor

const file_proto_simulation_proto_rawDesc = "" +
	"\n" +
	"\x16proto/simulation.proto\x12\x12fleetos.simulation\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x01\n" +
	"\x11ValidationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x120\n" +
	"\x14safety_envelope_json\x18\x03 \x01(\fR\x12safetyEnvelopeJson\x12%\n" +
	"\x0escenario_suite\x18\x04 \x01(\tR\rscenarioSuite\x12#\n" +
	"\rmax_scenarios\x18\x05 \x01(\x05R\fmaxScenarios\"\xd0\x02\n" +
	"\x10ValidationReport\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12)\n" +
	"\x10scenarios_passed\x18\x02 \x01(\x05R\x0fscenariosPassed\x12'\n" +
	"\x0fscenarios_total\x18\x03 \x01(\x05R\x0escenariosTotal\x12\x1b\n" +
	"\tpass_rate\x18\x04 \x01(\x01R\bpassRate\x12/\n" +
	"\x13deployment_approved\x18\x05 \x01(\bR\x12deploymentApproved\x12<\n" +
	"\aresults\x18\x06 \x03(\v2\".fleetos.simulation.ScenarioResultR\aresults\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x89\x03\n" +
	"\x0eScenarioResult\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x01R\x0fdurationSeconds\x12C\n" +
	"\n" +
	"violations\x18\x06 \x03(\v2#.fleetos.simulation.SafetyViolationR\n" +
	"violations\x12I\n" +
	"\ametrics\x18\a \x03(\v2/.fleetos.simulation.ScenarioResult.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x95\x01\n" +
	"\x0fSafetyViolation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x1c\n" +
	"\tmagnitude\x18\x03 \x01(\x01R\tmagnitude\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb8\x02\n" +
	"\x0fScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x120\n" +
	"\x14safety_envelope_json\x18\x04 \x01(\fR\x12safetyEnvelopeJson\x12S\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v23.fleetos.simulation.ScenarioRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x02\n" +
	"\rScenarioEvent\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12'\n" +
	"\x0felapsed_seconds\x18\x04 \x01(\x01R\x0eelapsedSeconds\x12H\n" +
	"\ametrics\x18\x05 \x03(\v2..fleetos.simulation.ScenarioEvent.MetricsEntryR\ametrics\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\",\n" +
	"\x14ListScenariosRequest\x12\x14\n" +
	"\x05suite\x18\x01 \x01(\tR\x05suite\"R\n" +
	"\x15ListScenariosResponse\x129\n" +
	"\x06suites\x18\x01 \x03(\v2!.fleetos.simulation.ScenarioSuiteR\x06suites\"\xac\x01\n" +
	"\rScenarioSuite\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12%\n" +
	"\x0escenario_count\x18\x03 \x01(\x05R\rscenarioCount\x12>\n" +
	"\tscenarios\x18\x04 \x03(\v2 .fleetos.simulation.ScenarioInfoR\tscenarios\"t\n" +
	"\fScenarioInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags2\xb0\x02\n" +
	"\x11SimulationService\x12\\\n" +
	"\rValidateAgent\x12%.fleetos.simulation.ValidationRequest\x1a$.fleetos.simulation.ValidationReport\x12W\n" +
	"\vRunScenario\x12#.fleetos.simulation.ScenarioRequest\x1a!.fleetos.simulation.ScenarioEvent0\x01\x12d\n" +
	"\rListScenarios\x12(.fleetos.simulation.ListScenariosRequest\x1a).fleetos.simulation.ListScenariosResponseB?Z=github.com/dimuthu/robot-fleet-playground/internal/simulationb\x06proto3"

var (
	file_proto_simulation_proto_rawDescOnce sync.Once
	file_proto_simulation_proto_rawDescData []byte
)

func file_proto_simulation_proto_rawDescGZIP() []byte {
	file_proto_simulation_proto_rawDescOnce.Do(func() {
		file_proto_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simulation_proto_rawDesc), len(file_proto_simulation_proto_rawDesc)))
	})
	return file_proto_simulation_proto_rawDescData
}

var file_proto_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_simulation_proto_goTypes = []any{
	(*ValidationRequest)(nil),     // 0: fleetos.simulation.ValidationRequest
	(*ValidationReport)(nil),      // 1: fleetos.simulation.ValidationReport
	(*ScenarioResult)(nil),        // 2: fleetos.simulation.ScenarioResult
	(*SafetyViolation)(nil),       // 3: fleetos.simulation.SafetyViolation
	(*ScenarioRequest)(nil),       // 4: fleetos.simulation.ScenarioRequest
	(*ScenarioEvent)(nil),         // 5: fleetos.simulation.ScenarioEvent
	(*ListScenariosRequest)(nil),  // 6: fleetos.simulation.ListScenariosRequest
	(*ListScenariosResponse)(nil), // 7: fleetos.simulation.ListScenariosResponse
	(*ScenarioSuite)(nil),         // 8: fleetos.simulation.ScenarioSuite
	(*ScenarioInfo)(nil),          // 9: fleetos.simulation.ScenarioInfo
	nil,                           // 10: fleetos.simulation.ScenarioResult.MetricsEntry
	nil,                           // 11: fleetos.simulation.ScenarioRequest.ParametersEntry
	nil,                           // 12: fleetos.simulation.ScenarioEvent.MetricsEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_proto_simulation_proto_depIdxs = []int32{
	2,  // 0: fleetos.simulation.ValidationReport.results:type_name -> fleetos.simulation.ScenarioResult
	13, // 1: fleetos.simulation.ValidationReport.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 2: fleetos.simulation.ScenarioResult.violations:type_name -> fleetos.simulation.SafetyViolation
	10, // 3: fleetos.simulation.ScenarioResult.metrics:type_name -> fleetos.simulation.ScenarioResult.MetricsEntry
	13, // 4: fleetos.simulation.SafetyViolation.timestamp:type_name -> google.protobuf.Timestamp
	11, // 5: fleetos.simulation.ScenarioRequest.parameters:type_name -> fleetos.simulation.ScenarioRequest.ParametersEntry
	12, // 6: fleetos.simulation.ScenarioEvent.metrics:type_name -> fleetos.simulation.ScenarioEvent.MetricsEntry
	13, // 7: fleetos.simulation.ScenarioEvent.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 8: fleetos.simulation.ListScenariosResponse.suites:type_name -> fleetos.simulation.ScenarioSuite
	9,  // 9: fleetos.simulation.ScenarioSuite.scenarios:type_name -> fleetos.simulation.ScenarioInfo
	0,  // 10: fleetos.simulation.SimulationService.ValidateAgent:input_type -> fleetos.simulation.ValidationRequest
	4,  // 11: fleetos.simulation.SimulationService.RunScenario:input_type -> fleetos.simulation.ScenarioRequest
	6,  // 12: fleetos.simulation.SimulationService.ListScenarios:input_type -> fleetos.simulation.ListScenariosRequest
	1,  // 13: fleetos.simulation.SimulationService.ValidateAgent:output_type -> fleetos.simulation.ValidationReport
	5,  // 14: fleetos.simulation.SimulationService.RunScenario:output_type -> fleetos.simulation.ScenarioEvent
	7,  // 15: fleetos.simulation.SimulationService.ListScenarios:output_type -> fleetos.simulation.ListScenariosResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_simulation_proto_init() }
func file_proto_simulation_proto_init() {
	if File_proto_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simulation_proto_rawDesc), len(file_proto_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_simulation_proto_goTypes,
		DependencyIndexes: file_proto_simulation_proto_depIdxs,
		MessageInfos:      file_proto_simulation_proto_msgTypes,
	}.Build()
	File_proto_simulation_proto = out.File
	file_proto_simulation_proto_goTypes = nil
	file_proto_simulation_proto_depIdxs = nil
}
