// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/simulation.proto

package simulation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulationService_ValidateAgent_FullMethodName = "/fleetos.simulation.SimulationService/ValidateAgent"
	SimulationService_RunScenario_FullMethodName   = "/fleetos.simulation.SimulationService/RunScenario"
	SimulationService_ListScenarios_FullMethodName = "/fleetos.simulation.SimulationService/ListScenarios"
)

// SimulationServiceClient is the client API for SimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SimulationService defines the Uranus-style validation interface.
// The playground implements this service; the platform calls it
// to validate agents before deployment to physical robots.
type SimulationServiceClient interface {
	// Validate an agent payload against a scenario suite.
	// Blocks until all scenarios complete; returns aggregate report.
	ValidateAgent(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationReport, error)
	// Run a single scenario with streaming progress events.
	RunScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScenarioEvent], error)
	// List available scenario suites and their scenario counts.
	ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error)
}

type simulationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationServiceClient(cc grpc.ClientConnInterface) SimulationServiceClient {
	return &simulationServiceClient{cc}
}

func (c *simulationServiceClient) ValidateAgent(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationReport)
	err := c.cc.Invoke(ctx, SimulationService_ValidateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) RunScenario(ctx context.Context, in *ScenarioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScenarioEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimulationService_ServiceDesc.Streams[0], SimulationService_RunScenario_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScenarioRequest, ScenarioEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationService_RunScenarioClient = grpc.ServerStreamingClient[ScenarioEvent]

func (c *simulationServiceClient) ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScenariosResponse)
	err := c.cc.Invoke(ctx, SimulationService_ListScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationServiceServer is the server API for SimulationService service.
// All implementations must embed UnimplementedSimulationServiceServer
// for forward compatibility.
//
// SimulationService defines the Uranus-style validation interface.
// The playground implements this service; the platform calls it
// to validate agents before deployment to physical robots.
type SimulationServiceServer interface {
	// Validate an agent payload against a scenario suite.
	// Blocks until all scenarios complete; returns aggregate report.
	ValidateAgent(context.Context, *ValidationRequest) (*ValidationReport, error)
	// Run a single scenario with streaming progress events.
	RunScenario(*ScenarioRequest, grpc.ServerStreamingServer[ScenarioEvent]) error
	// List available scenario suites and their scenario counts.
	ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error)
	mustEmbedUnimplementedSimulationServiceServer()
}

// UnimplementedSimulationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulationServiceServer struct{}

func (UnimplementedSimulationServiceServer) ValidateAgent(context.Context, *ValidationRequest) (*ValidationReport, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAgent not implemented")
}
func (UnimplementedSimulationServiceServer) RunScenario(*ScenarioRequest, grpc.ServerStreamingServer[ScenarioEvent]) error {
	return status.Error(codes.Unimplemented, "method RunScenario not implemented")
}
func (UnimplementedSimulationServiceServer) ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScenarios not implemented")
}
func (UnimplementedSimulationServiceServer) mustEmbedUnimplementedSimulationServiceServer() {}
func (UnimplementedSimulationServiceServer) testEmbeddedByValue()                           {}

// UnsafeSimulationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationServiceServer will
// result in compilation errors.
type UnsafeSimulationServiceServer interface {
	mustEmbedUnimplementedSimulationServiceServer()
}

func RegisterSimulationServiceServer(s grpc.ServiceRegistrar, srv SimulationServiceServer) {
	// If the following call panics, it indicates UnimplementedSimulationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulationService_ServiceDesc, srv)
}

func _SimulationService_ValidateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).ValidateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_ValidateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).ValidateAgent(ctx, req.(*ValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_RunScenario_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScenarioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulationServiceServer).RunScenario(m, &grpc.GenericServerStream[ScenarioRequest, ScenarioEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationService_RunScenarioServer = grpc.ServerStreamingServer[ScenarioEvent]

func _SimulationService_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_ListScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).ListScenarios(ctx, req.(*ListScenariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulationService_ServiceDesc is the grpc.ServiceDesc for SimulationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetos.simulation.SimulationService",
	HandlerType: (*SimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAgent",
			Handler:    _SimulationService_ValidateAgent_Handler,
		},
		{
			MethodName: "ListScenarios",
			Handler:    _SimulationService_ListScenarios_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunScenario",
			Handler:       _SimulationService_RunScenario_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/simulation.proto",
}
