// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/api.proto

package models

import (
	telemetry "github.com/dimuthu/robot-fleet/internal/telemetry"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Robot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LastPose      *telemetry.Pose        `protobuf:"bytes,5,opt,name=last_pose,json=lastPose,proto3" json:"last_pose,omitempty"`
	BatteryLevel  float64                `protobuf:"fixed64,6,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Robot) Reset() {
	*x = Robot{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Robot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Robot) ProtoMessage() {}

func (x *Robot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Robot.ProtoReflect.Descriptor instead.
func (*Robot) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *Robot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Robot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Robot) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Robot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Robot) GetLastPose() *telemetry.Pose {
	if x != nil {
		return x.LastPose
	}
	return nil
}

func (x *Robot) GetBatteryLevel() float64 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *Robot) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Robot) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Robot) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListRobotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRobotsRequest) Reset() {
	*x = ListRobotsRequest{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRobotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRobotsRequest) ProtoMessage() {}

func (x *ListRobotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRobotsRequest.ProtoReflect.Descriptor instead.
func (*ListRobotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListRobotsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRobotsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRobotsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListRobotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Robots        []*Robot               `protobuf:"bytes,1,rep,name=robots,proto3" json:"robots,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRobotsResponse) Reset() {
	*x = ListRobotsResponse{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRobotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRobotsResponse) ProtoMessage() {}

func (x *ListRobotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRobotsResponse.ProtoReflect.Descriptor instead.
func (*ListRobotsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListRobotsResponse) GetRobots() []*Robot {
	if x != nil {
		return x.Robots
	}
	return nil
}

func (x *ListRobotsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListRobotsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetRobotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRobotRequest) Reset() {
	*x = GetRobotRequest{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRobotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotRequest) ProtoMessage() {}

func (x *GetRobotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotRequest.ProtoReflect.Descriptor instead.
func (*GetRobotRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetRobotRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type SendCommandRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RobotId       string                  `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Command       *telemetry.RobotCommand `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *SendCommandRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *SendCommandRequest) GetCommand() *telemetry.RobotCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type SendCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *SendCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SendCommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryRequest) Reset() {
	*x = GetTelemetryRequest{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryRequest) ProtoMessage() {}

func (x *GetTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryRequest.ProtoReflect.Descriptor instead.
func (*GetTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetTelemetryRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *GetTelemetryRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *GetTelemetryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTelemetryResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Packets       []*telemetry.TelemetryPacket `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryResponse) Reset() {
	*x = GetTelemetryResponse{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryResponse) ProtoMessage() {}

func (x *GetTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryResponse.ProtoReflect.Descriptor instead.
func (*GetTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetTelemetryResponse) GetPackets() []*telemetry.TelemetryPacket {
	if x != nil {
		return x.Packets
	}
	return nil
}

type InferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Instruction   string                 `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *InferenceRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *InferenceRequest) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *InferenceRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type InferenceResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	PredictedJoints []*telemetry.JointState `protobuf:"bytes,1,rep,name=predicted_joints,json=predictedJoints,proto3" json:"predicted_joints,omitempty"`
	Confidence      float64                 `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ModelVersion    string                  `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	LatencyMs       int64                   `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *InferenceResponse) GetPredictedJoints() []*telemetry.JointState {
	if x != nil {
		return x.PredictedJoints
	}
	return nil
}

func (x *InferenceResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *InferenceResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *InferenceResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type FleetMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalRobots         int32                  `protobuf:"varint,1,opt,name=total_robots,json=totalRobots,proto3" json:"total_robots,omitempty"`
	ActiveRobots        int32                  `protobuf:"varint,2,opt,name=active_robots,json=activeRobots,proto3" json:"active_robots,omitempty"`
	IdleRobots          int32                  `protobuf:"varint,3,opt,name=idle_robots,json=idleRobots,proto3" json:"idle_robots,omitempty"`
	ErrorRobots         int32                  `protobuf:"varint,4,opt,name=error_robots,json=errorRobots,proto3" json:"error_robots,omitempty"`
	AvgBattery          float64                `protobuf:"fixed64,5,opt,name=avg_battery,json=avgBattery,proto3" json:"avg_battery,omitempty"`
	TelemetryRatePerSec int64                  `protobuf:"varint,6,opt,name=telemetry_rate_per_sec,json=telemetryRatePerSec,proto3" json:"telemetry_rate_per_sec,omitempty"`
	Timestamp           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FleetMetrics) Reset() {
	*x = FleetMetrics{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMetrics) ProtoMessage() {}

func (x *FleetMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMetrics.ProtoReflect.Descriptor instead.
func (*FleetMetrics) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *FleetMetrics) GetTotalRobots() int32 {
	if x != nil {
		return x.TotalRobots
	}
	return 0
}

func (x *FleetMetrics) GetActiveRobots() int32 {
	if x != nil {
		return x.ActiveRobots
	}
	return 0
}

func (x *FleetMetrics) GetIdleRobots() int32 {
	if x != nil {
		return x.IdleRobots
	}
	return 0
}

func (x *FleetMetrics) GetErrorRobots() int32 {
	if x != nil {
		return x.ErrorRobots
	}
	return 0
}

func (x *FleetMetrics) GetAvgBattery() float64 {
	if x != nil {
		return x.AvgBattery
	}
	return 0
}

func (x *FleetMetrics) GetTelemetryRatePerSec() int64 {
	if x != nil {
		return x.TelemetryRatePerSec
	}
	return 0
}

func (x *FleetMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type FleetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetMetricsRequest) Reset() {
	*x = FleetMetricsRequest{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMetricsRequest) ProtoMessage() {}

func (x *FleetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMetricsRequest.ProtoReflect.Descriptor instead.
func (*FleetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\x12\vfleetos.api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15proto/telemetry.proto\"\xa9\x03\n" +
	"\x05Robot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x124\n" +
	"\tlast_pose\x18\x05 \x01(\v2\x17.fleetos.telemetry.PoseR\blastPose\x12#\n" +
	"\rbattery_level\x18\x06 \x01(\x01R\fbatteryLevel\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12?\n" +
	"\rregistered_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12<\n" +
	"\bmetadata\x18\t \x03(\v2 .fleetos.api.Robot.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x11ListRobotsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\"\x89\x01\n" +
	"\x12ListRobotsResponse\x12*\n" +
	"\x06robots\x18\x01 \x03(\v2\x12.fleetos.api.RobotR\x06robots\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\",\n" +
	"\x0fGetRobotRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\"j\n" +
	"\x12SendCommandRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x129\n" +
	"\acommand\x18\x02 \x01(\v2\x1f.fleetos.telemetry.RobotCommandR\acommand\"L\n" +
	"\x13SendCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"x\n" +
	"\x13GetTelemetryRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"T\n" +
	"\x14GetTelemetryResponse\x12<\n" +
	"\apackets\x18\x01 \x03(\v2\".fleetos.telemetry.TelemetryPacketR\apackets\"e\n" +
	"\x10InferenceRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12 \n" +
	"\vinstruction\x18\x02 \x01(\tR\vinstruction\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\"\xc1\x01\n" +
	"\x11InferenceResponse\x12H\n" +
	"\x10predicted_joints\x18\x01 \x03(\v2\x1d.fleetos.telemetry.JointStateR\x0fpredictedJoints\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\"\xaa\x02\n" +
	"\fFleetMetrics\x12!\n" +
	"\ftotal_robots\x18\x01 \x01(\x05R\vtotalRobots\x12#\n" +
	"\ractive_robots\x18\x02 \x01(\x05R\factiveRobots\x12\x1f\n" +
	"\vidle_robots\x18\x03 \x01(\x05R\n" +
	"idleRobots\x12!\n" +
	"\ferror_robots\x18\x04 \x01(\x05R\verrorRobots\x12\x1f\n" +
	"\vavg_battery\x18\x05 \x01(\x01R\n" +
	"avgBattery\x123\n" +
	"\x16telemetry_rate_per_sec\x18\x06 \x01(\x03R\x13telemetryRatePerSec\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x15\n" +
	"\x13FleetMetricsRequest2\xe1\x03\n" +
	"\fFleetService\x12M\n" +
	"\n" +
	"ListRobots\x12\x1e.fleetos.api.ListRobotsRequest\x1a\x1f.fleetos.api.ListRobotsResponse\x12<\n" +
	"\bGetRobot\x12\x1c.fleetos.api.GetRobotRequest\x1a\x12.fleetos.api.Robot\x12P\n" +
	"\vSendCommand\x12\x1f.fleetos.api.SendCommandRequest\x1a .fleetos.api.SendCommandResponse\x12S\n" +
	"\fGetTelemetry\x12 .fleetos.api.GetTelemetryRequest\x1a!.fleetos.api.GetTelemetryResponse\x12M\n" +
	"\fRunInference\x12\x1d.fleetos.api.InferenceRequest\x1a\x1e.fleetos.api.InferenceResponse\x12N\n" +
	"\x0fGetFleetMetrics\x12 .fleetos.api.FleetMetricsRequest\x1a\x19.fleetos.api.FleetMetricsB0Z.github.com/dimuthu/robot-fleet/internal/modelsb\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_api_proto_goTypes = []any{
	(*Robot)(nil),                     // 0: fleetos.api.Robot
	(*ListRobotsRequest)(nil),         // 1: fleetos.api.ListRobotsRequest
	(*ListRobotsResponse)(nil),        // 2: fleetos.api.ListRobotsResponse
	(*GetRobotRequest)(nil),           // 3: fleetos.api.GetRobotRequest
	(*SendCommandRequest)(nil),        // 4: fleetos.api.SendCommandRequest
	(*SendCommandResponse)(nil),       // 5: fleetos.api.SendCommandResponse
	(*GetTelemetryRequest)(nil),       // 6: fleetos.api.GetTelemetryRequest
	(*GetTelemetryResponse)(nil),      // 7: fleetos.api.GetTelemetryResponse
	(*InferenceRequest)(nil),          // 8: fleetos.api.InferenceRequest
	(*InferenceResponse)(nil),         // 9: fleetos.api.InferenceResponse
	(*FleetMetrics)(nil),              // 10: fleetos.api.FleetMetrics
	(*FleetMetricsRequest)(nil),       // 11: fleetos.api.FleetMetricsRequest
	nil,                               // 12: fleetos.api.Robot.MetadataEntry
	(*telemetry.Pose)(nil),            // 13: fleetos.telemetry.Pose
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
	(*telemetry.RobotCommand)(nil),    // 15: fleetos.telemetry.RobotCommand
	(*telemetry.TelemetryPacket)(nil), // 16: fleetos.telemetry.TelemetryPacket
	(*telemetry.JointState)(nil),      // 17: fleetos.telemetry.JointState
}
var file_proto_api_proto_depIdxs = []int32{
	13, // 0: fleetos.api.Robot.last_pose:type_name -> fleetos.telemetry.Pose
	14, // 1: fleetos.api.Robot.last_seen:type_name -> google.protobuf.Timestamp
	14, // 2: fleetos.api.Robot.registered_at:type_name -> google.protobuf.Timestamp
	12, // 3: fleetos.api.Robot.metadata:type_name -> fleetos.api.Robot.MetadataEntry
	0,  // 4: fleetos.api.ListRobotsResponse.robots:type_name -> fleetos.api.Robot
	15, // 5: fleetos.api.SendCommandRequest.command:type_name -> fleetos.telemetry.RobotCommand
	14, // 6: fleetos.api.GetTelemetryRequest.since:type_name -> google.protobuf.Timestamp
	16, // 7: fleetos.api.GetTelemetryResponse.packets:type_name -> fleetos.telemetry.TelemetryPacket
	17, // 8: fleetos.api.InferenceResponse.predicted_joints:type_name -> fleetos.telemetry.JointState
	14, // 9: fleetos.api.FleetMetrics.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 10: fleetos.api.FleetService.ListRobots:input_type -> fleetos.api.ListRobotsRequest
	3,  // 11: fleetos.api.FleetService.GetRobot:input_type -> fleetos.api.GetRobotRequest
	4,  // 12: fleetos.api.FleetService.SendCommand:input_type -> fleetos.api.SendCommandRequest
	6,  // 13: fleetos.api.FleetService.GetTelemetry:input_type -> fleetos.api.GetTelemetryRequest
	8,  // 14: fleetos.api.FleetService.RunInference:input_type -> fleetos.api.InferenceRequest
	11, // 15: fleetos.api.FleetService.GetFleetMetrics:input_type -> fleetos.api.FleetMetricsRequest
	2,  // 16: fleetos.api.FleetService.ListRobots:output_type -> fleetos.api.ListRobotsResponse
	0,  // 17: fleetos.api.FleetService.GetRobot:output_type -> fleetos.api.Robot
	5,  // 18: fleetos.api.FleetService.SendCommand:output_type -> fleetos.api.SendCommandResponse
	7,  // 19: fleetos.api.FleetService.GetTelemetry:output_type -> fleetos.api.GetTelemetryResponse
	9,  // 20: fleetos.api.FleetService.RunInference:output_type -> fleetos.api.InferenceResponse
	10, // 21: fleetos.api.FleetService.GetFleetMetrics:output_type -> fleetos.api.FleetMetrics
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
