// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Quaternion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	W             float64                `protobuf:"fixed64,4,opt,name=w,proto3" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quaternion) Reset() {
	*x = Quaternion{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quaternion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quaternion) ProtoMessage() {}

func (x *Quaternion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quaternion.ProtoReflect.Descriptor instead.
func (*Quaternion) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Quaternion) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Quaternion) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Quaternion) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Quaternion) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

type JointState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Position      float64                `protobuf:"fixed64,2,opt,name=position,proto3" json:"position,omitempty"` // radians
	Velocity      float64                `protobuf:"fixed64,3,opt,name=velocity,proto3" json:"velocity,omitempty"` // rad/s
	Torque        float64                `protobuf:"fixed64,4,opt,name=torque,proto3" json:"torque,omitempty"`     // Nm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JointState) Reset() {
	*x = JointState{}
	mi := &file_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JointState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointState) ProtoMessage() {}

func (x *JointState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointState.ProtoReflect.Descriptor instead.
func (*JointState) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *JointState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JointState) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *JointState) GetVelocity() float64 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *JointState) GetTorque() float64 {
	if x != nil {
		return x.Torque
	}
	return 0
}

type LidarPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Intensity     float32                `protobuf:"fixed32,4,opt,name=intensity,proto3" json:"intensity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LidarPoint) Reset() {
	*x = LidarPoint{}
	mi := &file_proto_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LidarPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LidarPoint) ProtoMessage() {}

func (x *LidarPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LidarPoint.ProtoReflect.Descriptor instead.
func (*LidarPoint) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *LidarPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *LidarPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *LidarPoint) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *LidarPoint) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

type LidarScan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*LidarPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LidarScan) Reset() {
	*x = LidarScan{}
	mi := &file_proto_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LidarScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LidarScan) ProtoMessage() {}

func (x *LidarScan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LidarScan.ProtoReflect.Descriptor instead.
func (*LidarScan) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *LidarScan) GetPoints() []*LidarPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *LidarScan) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type VideoFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`         // JPEG/H264 encoded frame
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"` // "jpeg", "h264"
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFrame) Reset() {
	*x = VideoFrame{}
	mi := &file_proto_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrame) ProtoMessage() {}

func (x *VideoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrame.ProtoReflect.Descriptor instead.
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *VideoFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoFrame) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *VideoFrame) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoFrame) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoFrame) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                // PCM audio data
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // e.g., 16000
	Channels      int32                  `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioChunk) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Pose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vector3               `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Orientation   *Quaternion            `protobuf:"bytes,2,opt,name=orientation,proto3" json:"orientation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pose) Reset() {
	*x = Pose{}
	mi := &file_proto_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pose) ProtoMessage() {}

func (x *Pose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pose.ProtoReflect.Descriptor instead.
func (*Pose) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *Pose) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Pose) GetOrientation() *Quaternion {
	if x != nil {
		return x.Orientation
	}
	return nil
}

type RobotState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Pose          *Pose                  `protobuf:"bytes,2,opt,name=pose,proto3" json:"pose,omitempty"`
	Joints        []*JointState          `protobuf:"bytes,3,rep,name=joints,proto3" json:"joints,omitempty"`
	BatteryLevel  float64                `protobuf:"fixed64,4,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"` // 0.0 - 1.0
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                   // "idle", "active", "charging", "error"
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotState) Reset() {
	*x = RobotState{}
	mi := &file_proto_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotState) ProtoMessage() {}

func (x *RobotState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotState.ProtoReflect.Descriptor instead.
func (*RobotState) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *RobotState) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *RobotState) GetPose() *Pose {
	if x != nil {
		return x.Pose
	}
	return nil
}

func (x *RobotState) GetJoints() []*JointState {
	if x != nil {
		return x.Joints
	}
	return nil
}

func (x *RobotState) GetBatteryLevel() float64 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *RobotState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RobotState) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TelemetryPacket struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RobotId   string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TelemetryPacket_State
	//	*TelemetryPacket_Video
	//	*TelemetryPacket_Lidar
	//	*TelemetryPacket_Audio
	Payload       isTelemetryPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPacket) Reset() {
	*x = TelemetryPacket{}
	mi := &file_proto_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPacket) ProtoMessage() {}

func (x *TelemetryPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPacket.ProtoReflect.Descriptor instead.
func (*TelemetryPacket) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *TelemetryPacket) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *TelemetryPacket) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TelemetryPacket) GetPayload() isTelemetryPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryPacket) GetState() *RobotState {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryPacket_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *TelemetryPacket) GetVideo() *VideoFrame {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryPacket_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *TelemetryPacket) GetLidar() *LidarScan {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryPacket_Lidar); ok {
			return x.Lidar
		}
	}
	return nil
}

func (x *TelemetryPacket) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Payload.(*TelemetryPacket_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

type isTelemetryPacket_Payload interface {
	isTelemetryPacket_Payload()
}

type TelemetryPacket_State struct {
	State *RobotState `protobuf:"bytes,3,opt,name=state,proto3,oneof"`
}

type TelemetryPacket_Video struct {
	Video *VideoFrame `protobuf:"bytes,4,opt,name=video,proto3,oneof"`
}

type TelemetryPacket_Lidar struct {
	Lidar *LidarScan `protobuf:"bytes,5,opt,name=lidar,proto3,oneof"`
}

type TelemetryPacket_Audio struct {
	Audio *AudioChunk `protobuf:"bytes,6,opt,name=audio,proto3,oneof"`
}

func (*TelemetryPacket_State) isTelemetryPacket_Payload() {}

func (*TelemetryPacket_Video) isTelemetryPacket_Payload() {}

func (*TelemetryPacket_Lidar) isTelemetryPacket_Payload() {}

func (*TelemetryPacket_Audio) isTelemetryPacket_Payload() {}

type RobotCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RobotId   string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	CommandId string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*RobotCommand_Move
	//	*RobotCommand_Joint
	//	*RobotCommand_Stop
	Action        isRobotCommand_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotCommand) Reset() {
	*x = RobotCommand{}
	mi := &file_proto_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotCommand) ProtoMessage() {}

func (x *RobotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotCommand.ProtoReflect.Descriptor instead.
func (*RobotCommand) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{10}
}

func (x *RobotCommand) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *RobotCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RobotCommand) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RobotCommand) GetAction() isRobotCommand_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *RobotCommand) GetMove() *MoveCommand {
	if x != nil {
		if x, ok := x.Action.(*RobotCommand_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *RobotCommand) GetJoint() *JointCommand {
	if x != nil {
		if x, ok := x.Action.(*RobotCommand_Joint); ok {
			return x.Joint
		}
	}
	return nil
}

func (x *RobotCommand) GetStop() *StopCommand {
	if x != nil {
		if x, ok := x.Action.(*RobotCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

type isRobotCommand_Action interface {
	isRobotCommand_Action()
}

type RobotCommand_Move struct {
	Move *MoveCommand `protobuf:"bytes,4,opt,name=move,proto3,oneof"`
}

type RobotCommand_Joint struct {
	Joint *JointCommand `protobuf:"bytes,5,opt,name=joint,proto3,oneof"`
}

type RobotCommand_Stop struct {
	Stop *StopCommand `protobuf:"bytes,6,opt,name=stop,proto3,oneof"`
}

func (*RobotCommand_Move) isRobotCommand_Action() {}

func (*RobotCommand_Joint) isRobotCommand_Action() {}

func (*RobotCommand_Stop) isRobotCommand_Action() {}

type MoveCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetPosition *Vector3               `protobuf:"bytes,1,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	MaxVelocity    float64                `protobuf:"fixed64,2,opt,name=max_velocity,json=maxVelocity,proto3" json:"max_velocity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MoveCommand) Reset() {
	*x = MoveCommand{}
	mi := &file_proto_telemetry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCommand) ProtoMessage() {}

func (x *MoveCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCommand.ProtoReflect.Descriptor instead.
func (*MoveCommand) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{11}
}

func (x *MoveCommand) GetTargetPosition() *Vector3 {
	if x != nil {
		return x.TargetPosition
	}
	return nil
}

func (x *MoveCommand) GetMaxVelocity() float64 {
	if x != nil {
		return x.MaxVelocity
	}
	return 0
}

type JointCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetJoints    []*JointState          `protobuf:"bytes,1,rep,name=target_joints,json=targetJoints,proto3" json:"target_joints,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JointCommand) Reset() {
	*x = JointCommand{}
	mi := &file_proto_telemetry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JointCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointCommand) ProtoMessage() {}

func (x *JointCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointCommand.ProtoReflect.Descriptor instead.
func (*JointCommand) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{12}
}

func (x *JointCommand) GetTargetJoints() []*JointState {
	if x != nil {
		return x.TargetJoints
	}
	return nil
}

func (x *JointCommand) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type StopCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emergency     bool                   `protobuf:"varint,1,opt,name=emergency,proto3" json:"emergency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCommand) Reset() {
	*x = StopCommand{}
	mi := &file_proto_telemetry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCommand) ProtoMessage() {}

func (x *StopCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCommand.ProtoReflect.Descriptor instead.
func (*StopCommand) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{13}
}

func (x *StopCommand) GetEmergency() bool {
	if x != nil {
		return x.Emergency
	}
	return false
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_proto_telemetry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{14}
}

func (x *StreamAck) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *StreamAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{15}
}

func (x *CommandRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\x11fleetos.telemetry\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"D\n" +
	"\n" +
	"Quaternion\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\x12\f\n" +
	"\x01w\x18\x04 \x01(\x01R\x01w\"p\n" +
	"\n" +
	"JointState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x01R\bposition\x12\x1a\n" +
	"\bvelocity\x18\x03 \x01(\x01R\bvelocity\x12\x16\n" +
	"\x06torque\x18\x04 \x01(\x01R\x06torque\"T\n" +
	"\n" +
	"LidarPoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x1c\n" +
	"\tintensity\x18\x04 \x01(\x02R\tintensity\"|\n" +
	"\tLidarScan\x125\n" +
	"\x06points\x18\x01 \x03(\v2\x1d.fleetos.telemetry.LidarPointR\x06points\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa4\x01\n" +
	"\n" +
	"VideoFrame\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x97\x01\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\x05R\bchannels\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x7f\n" +
	"\x04Pose\x126\n" +
	"\bposition\x18\x01 \x01(\v2\x1a.fleetos.telemetry.Vector3R\bposition\x12?\n" +
	"\vorientation\x18\x02 \x01(\v2\x1d.fleetos.telemetry.QuaternionR\vorientation\"\x82\x02\n" +
	"\n" +
	"RobotState\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12+\n" +
	"\x04pose\x18\x02 \x01(\v2\x17.fleetos.telemetry.PoseR\x04pose\x125\n" +
	"\x06joints\x18\x03 \x03(\v2\x1d.fleetos.telemetry.JointStateR\x06joints\x12#\n" +
	"\rbattery_level\x18\x04 \x01(\x01R\fbatteryLevel\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xcc\x02\n" +
	"\x0fTelemetryPacket\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\x05state\x18\x03 \x01(\v2\x1d.fleetos.telemetry.RobotStateH\x00R\x05state\x125\n" +
	"\x05video\x18\x04 \x01(\v2\x1d.fleetos.telemetry.VideoFrameH\x00R\x05video\x124\n" +
	"\x05lidar\x18\x05 \x01(\v2\x1c.fleetos.telemetry.LidarScanH\x00R\x05lidar\x125\n" +
	"\x05audio\x18\x06 \x01(\v2\x1d.fleetos.telemetry.AudioChunkH\x00R\x05audioB\t\n" +
	"\apayload\"\xb1\x02\n" +
	"\fRobotCommand\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x124\n" +
	"\x04move\x18\x04 \x01(\v2\x1e.fleetos.telemetry.MoveCommandH\x00R\x04move\x127\n" +
	"\x05joint\x18\x05 \x01(\v2\x1f.fleetos.telemetry.JointCommandH\x00R\x05joint\x124\n" +
	"\x04stop\x18\x06 \x01(\v2\x1e.fleetos.telemetry.StopCommandH\x00R\x04stopB\b\n" +
	"\x06action\"u\n" +
	"\vMoveCommand\x12C\n" +
	"\x0ftarget_position\x18\x01 \x01(\v2\x1a.fleetos.telemetry.Vector3R\x0etargetPosition\x12!\n" +
	"\fmax_velocity\x18\x02 \x01(\x01R\vmaxVelocity\"}\n" +
	"\fJointCommand\x12B\n" +
	"\rtarget_joints\x18\x01 \x03(\v2\x1d.fleetos.telemetry.JointStateR\ftargetJoints\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x01R\x0fdurationSeconds\"+\n" +
	"\vStopCommand\x12\x1c\n" +
	"\temergency\x18\x01 \x01(\bR\temergency\"D\n" +
	"\tStreamAck\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"+\n" +
	"\x0eCommandRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId2\xc3\x01\n" +
	"\x10TelemetryService\x12W\n" +
	"\x0fStreamTelemetry\x12\".fleetos.telemetry.TelemetryPacket\x1a\x1c.fleetos.telemetry.StreamAck(\x010\x01\x12V\n" +
	"\x0eStreamCommands\x12!.fleetos.telemetry.CommandRequest\x1a\x1f.fleetos.telemetry.RobotCommand0\x01B3Z1github.com/dimuthu/robot-fleet/internal/telemetryb\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_telemetry_proto_goTypes = []any{
	(*Vector3)(nil),               // 0: fleetos.telemetry.Vector3
	(*Quaternion)(nil),            // 1: fleetos.telemetry.Quaternion
	(*JointState)(nil),            // 2: fleetos.telemetry.JointState
	(*LidarPoint)(nil),            // 3: fleetos.telemetry.LidarPoint
	(*LidarScan)(nil),             // 4: fleetos.telemetry.LidarScan
	(*VideoFrame)(nil),            // 5: fleetos.telemetry.VideoFrame
	(*AudioChunk)(nil),            // 6: fleetos.telemetry.AudioChunk
	(*Pose)(nil),                  // 7: fleetos.telemetry.Pose
	(*RobotState)(nil),            // 8: fleetos.telemetry.RobotState
	(*TelemetryPacket)(nil),       // 9: fleetos.telemetry.TelemetryPacket
	(*RobotCommand)(nil),          // 10: fleetos.telemetry.RobotCommand
	(*MoveCommand)(nil),           // 11: fleetos.telemetry.MoveCommand
	(*JointCommand)(nil),          // 12: fleetos.telemetry.JointCommand
	(*StopCommand)(nil),           // 13: fleetos.telemetry.StopCommand
	(*StreamAck)(nil),             // 14: fleetos.telemetry.StreamAck
	(*CommandRequest)(nil),        // 15: fleetos.telemetry.CommandRequest
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_proto_telemetry_proto_depIdxs = []int32{
	3,  // 0: fleetos.telemetry.LidarScan.points:type_name -> fleetos.telemetry.LidarPoint
	16, // 1: fleetos.telemetry.LidarScan.timestamp:type_name -> google.protobuf.Timestamp
	16, // 2: fleetos.telemetry.VideoFrame.timestamp:type_name -> google.protobuf.Timestamp
	16, // 3: fleetos.telemetry.AudioChunk.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 4: fleetos.telemetry.Pose.position:type_name -> fleetos.telemetry.Vector3
	1,  // 5: fleetos.telemetry.Pose.orientation:type_name -> fleetos.telemetry.Quaternion
	7,  // 6: fleetos.telemetry.RobotState.pose:type_name -> fleetos.telemetry.Pose
	2,  // 7: fleetos.telemetry.RobotState.joints:type_name -> fleetos.telemetry.JointState
	16, // 8: fleetos.telemetry.RobotState.timestamp:type_name -> google.protobuf.Timestamp
	16, // 9: fleetos.telemetry.TelemetryPacket.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 10: fleetos.telemetry.TelemetryPacket.state:type_name -> fleetos.telemetry.RobotState
	5,  // 11: fleetos.telemetry.TelemetryPacket.video:type_name -> fleetos.telemetry.VideoFrame
	4,  // 12: fleetos.telemetry.TelemetryPacket.lidar:type_name -> fleetos.telemetry.LidarScan
	6,  // 13: fleetos.telemetry.TelemetryPacket.audio:type_name -> fleetos.telemetry.AudioChunk
	16, // 14: fleetos.telemetry.RobotCommand.timestamp:type_name -> google.protobuf.Timestamp
	11, // 15: fleetos.telemetry.RobotCommand.move:type_name -> fleetos.telemetry.MoveCommand
	12, // 16: fleetos.telemetry.RobotCommand.joint:type_name -> fleetos.telemetry.JointCommand
	13, // 17: fleetos.telemetry.RobotCommand.stop:type_name -> fleetos.telemetry.StopCommand
	0,  // 18: fleetos.telemetry.MoveCommand.target_position:type_name -> fleetos.telemetry.Vector3
	2,  // 19: fleetos.telemetry.JointCommand.target_joints:type_name -> fleetos.telemetry.JointState
	9,  // 20: fleetos.telemetry.TelemetryService.StreamTelemetry:input_type -> fleetos.telemetry.TelemetryPacket
	15, // 21: fleetos.telemetry.TelemetryService.StreamCommands:input_type -> fleetos.telemetry.CommandRequest
	14, // 22: fleetos.telemetry.TelemetryService.StreamTelemetry:output_type -> fleetos.telemetry.StreamAck
	10, // 23: fleetos.telemetry.TelemetryService.StreamCommands:output_type -> fleetos.telemetry.RobotCommand
	22, // [22:24] is the sub-list for method output_type
	20, // [20:22] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	file_proto_telemetry_proto_msgTypes[9].OneofWrappers = []any{
		(*TelemetryPacket_State)(nil),
		(*TelemetryPacket_Video)(nil),
		(*TelemetryPacket_Lidar)(nil),
		(*TelemetryPacket_Audio)(nil),
	}
	file_proto_telemetry_proto_msgTypes[10].OneofWrappers = []any{
		(*RobotCommand_Move)(nil),
		(*RobotCommand_Joint)(nil),
		(*RobotCommand_Stop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
