package middleware

import (
	"bufio"
	"fmt"
	"net"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	httpRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_api_requests_total",
		Help: "Total HTTP requests by method, path, and status",
	}, []string{"method", "path", "status"})

	httpRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "fleetos_api_request_duration_seconds",
		Help:    "HTTP request duration in seconds",
		Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
	}, []string{"method", "path"})

	activeConnections = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "fleetos_api_active_connections",
		Help: "Number of active HTTP connections",
	})

	TelemetryPacketsTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "fleetos_telemetry_packets_total",
		Help: "Total telemetry packets processed",
	})

	RobotsTotal = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "fleetos_robots_total",
		Help: "Total number of registered robots",
	})

	RobotsActive = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "fleetos_robots_active",
		Help: "Number of active robots",
	})

	RobotsError = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "fleetos_robots_error",
		Help: "Number of robots in error state",
	})

	AvgBatteryLevel = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "fleetos_avg_battery_level",
		Help: "Average battery level across all robots (0-1)",
	})

	KafkaConsumerLag = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "fleetos_kafka_consumer_lag",
		Help: "Kafka consumer lag (messages behind)",
	})

	InferenceDuration = promauto.NewHistogram(prometheus.HistogramOpts{
		Name:    "fleetos_inference_duration_seconds",
		Help:    "AI inference request duration",
		Buckets: []float64{0.01, 0.05, 0.1, 0.5, 1, 2, 5, 10},
	})

	TenantAPIUsage = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_tenant_api_calls_total",
		Help: "API calls per tenant",
	}, []string{"tenant_id"})

	WebSocketConnections = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "fleetos_websocket_connections",
		Help: "Active WebSocket connections",
	})

	CommandDispatchDuration = promauto.NewHistogram(prometheus.HistogramOpts{
		Name:    "fleetos_command_dispatch_duration_seconds",
		Help:    "End-to-end command dispatch latency (API to robot ack)",
		Buckets: []float64{0.01, 0.025, 0.05, 0.1, 0.2, 0.5, 1, 2},
	})

	CommandsDispatched = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_commands_dispatched_total",
		Help: "Total commands dispatched to robots",
	}, []string{"command_type", "status"})

	// --- gRPC Stream Metrics ---

	GRPCActiveStreams = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "fleetos_grpc_active_streams",
		Help: "Active gRPC bidirectional streams",
	}, []string{"stream_type"}) // "telemetry", "commands"

	GRPCStreamMessagesTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_grpc_stream_messages_total",
		Help: "Total gRPC stream messages by type and direction",
	}, []string{"stream_type", "direction"}) // direction: "sent", "received"

	GRPCStreamDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "fleetos_grpc_stream_duration_seconds",
		Help:    "Duration of gRPC streams",
		Buckets: []float64{1, 5, 10, 30, 60, 300, 600, 1800, 3600},
	}, []string{"stream_type"})

	GRPCStreamErrors = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_grpc_stream_errors_total",
		Help: "Total gRPC stream errors",
	}, []string{"stream_type", "code"})

	// --- Temporal Workflow Metrics ---

	TemporalWorkflowsStarted = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_temporal_workflows_started_total",
		Help: "Temporal workflows started by type",
	}, []string{"workflow_type"})

	TemporalWorkflowsCompleted = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_temporal_workflows_completed_total",
		Help: "Temporal workflows completed by type and status",
	}, []string{"workflow_type", "status"}) // status: "completed", "failed", "timed_out"

	TemporalActiveWorkflows = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "fleetos_temporal_active_workflows",
		Help: "Currently running Temporal workflows by type",
	}, []string{"workflow_type"})

	// --- Billing Metrics ---

	BillingUsageAggregated = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_billing_usage_aggregated_total",
		Help: "Usage aggregation events by tenant and metric",
	}, []string{"tenant_id", "metric"})

	BillingInvoicesGenerated = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_billing_invoices_generated_total",
		Help: "Invoices generated by status",
	}, []string{"status"}) // "draft", "paid", "failed"

	BillingPaymentAttempts = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_billing_payment_attempts_total",
		Help: "Payment attempts by outcome",
	}, []string{"outcome"}) // "succeeded", "failed", "skipped"

	// --- Training / ML Metrics ---

	TrainingJobsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_training_jobs_total",
		Help: "Training jobs by status",
	}, []string{"status"}) // "submitted", "completed", "failed", "gated"

	TrainingDuration = promauto.NewHistogram(prometheus.HistogramOpts{
		Name:    "fleetos_training_duration_seconds",
		Help:    "Training job duration",
		Buckets: []float64{60, 300, 600, 1800, 3600, 7200, 14400},
	})

	ModelDeploymentsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "fleetos_model_deployments_total",
		Help: "Model deployments by outcome",
	}, []string{"outcome"}) // "deployed", "rolled_back"

	ModelSuccessRate = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "fleetos_model_success_rate",
		Help: "Current model success_rate (uptime) from live fleet",
	}, []string{"model_id"})

	// --- Per-Robot Metrics ---

	RobotBatteryLevel = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "fleetos_robot_battery_level",
		Help: "Battery level per robot (0-1)",
	}, []string{"robot_id"})

	RobotLastSeenTimestamp = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "fleetos_robot_last_seen_timestamp",
		Help: "Unix timestamp of last telemetry from robot",
	}, []string{"robot_id"})

	RobotReward = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "fleetos_robot_reward",
		Help: "Current episode reward per robot",
	}, []string{"robot_id"})

	RobotUptimePct = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "fleetos_robot_uptime_pct",
		Help: "Uptime percentage per robot (0-1)",
	}, []string{"robot_id"})

	RobotFallCount = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "fleetos_robot_fall_count",
		Help: "Total falls per robot",
	}, []string{"robot_id"})

	RobotInferenceModel = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "fleetos_robot_inference_model_info",
		Help: "Robot model assignment (value=1, labels carry info)",
	}, []string{"robot_id", "model_id"})

	// --- Experience Collection Metrics ---

	ExperienceTransitionsTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "fleetos_experience_transitions_total",
		Help: "Total RL experience transitions collected",
	})

	ExperienceBatchesWritten = promauto.NewCounter(prometheus.CounterOpts{
		Name: "fleetos_experience_batches_written_total",
		Help: "Total experience batches written to S3",
	})
)

// MetricsHandler returns the Prometheus metrics HTTP handler.
func MetricsHandler() http.Handler {
	return promhttp.Handler()
}

// Metrics middleware records request count and duration.
func Metrics(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/metrics" || r.URL.Path == "/healthz" {
			next.ServeHTTP(w, r)
			return
		}

		activeConnections.Inc()
		defer activeConnections.Dec()

		start := time.Now()
		rw := &metricsResponseWriter{ResponseWriter: w, statusCode: http.StatusOK}

		next.ServeHTTP(rw, r)

		duration := time.Since(start).Seconds()
		status := strconv.Itoa(rw.statusCode)
		path := normalizePath(r.URL.Path)

		httpRequestsTotal.WithLabelValues(r.Method, path, status).Inc()
		httpRequestDuration.WithLabelValues(r.Method, path).Observe(duration)
	})
}

type metricsResponseWriter struct {
	http.ResponseWriter
	statusCode int
}

func (w *metricsResponseWriter) WriteHeader(code int) {
	w.statusCode = code
	w.ResponseWriter.WriteHeader(code)
}

// Hijack implements http.Hijacker so WebSocket upgrades work through the metrics middleware.
func (w *metricsResponseWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	if hj, ok := w.ResponseWriter.(http.Hijacker); ok {
		return hj.Hijack()
	}
	return nil, nil, fmt.Errorf("upstream ResponseWriter does not implement http.Hijacker")
}

// normalizePath reduces cardinality by replacing IDs with {id}.
func normalizePath(path string) string {
	// /api/v1/robots/robot-0001/command → /api/v1/robots/{id}/command
	parts := splitPath(path)
	for i, p := range parts {
		if (len(p) >= 6 && p[:6] == "robot-") || (len(p) > 4 && isNumeric(p)) {
			parts[i] = "{id}"
		}
	}
	return joinPath(parts)
}

func splitPath(p string) []string {
	var parts []string
	for _, s := range strings.Split(p, "/") {
		if s != "" {
			parts = append(parts, s)
		}
	}
	return parts
}

func joinPath(parts []string) string {
	return "/" + strings.Join(parts, "/")
}

func isNumeric(s string) bool {
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return len(s) > 0
}
